---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "dex-operator.labels" . | nindent 4 }}
  name:  {{ include "dex-operator.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name:  {{ include "dex-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "dex-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "dex-operator.labels" . | nindent 4 }}
  name: {{ include "dex-operator.fullname" . }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dex-operator.fullname" . }}-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "dex-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}