apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "dex-operator.labels" . | nindent 4 }}
  name: {{ include "dex-operator.fullname" . }}-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dex-operator.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "dex-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}