apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "dex-operator.labels" . | nindent 4 }}
  name: {{ include "dex-operator.fullname" . }}-controller-manager-metrics-monitor
spec:
  endpoints:
  - path: /metrics
    port: https
  selector:
    matchLabels:
      {{- include "dex-operator.selectorLabels" . | nindent 6 }}