apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: controller:latest
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - name: liveness-port
          containerPort: 9440
          hostPort: 9440
        livenessProbe:
          httpGet:
            path: /healthz
            port: liveness-port
        volumeMounts:
          - name: dex-grpc-client-cert
            mountPath: /etc/dex/tls
      terminationGracePeriodSeconds: 10
      volumes:
      - name: dex-grpc-client-cert
        secret:
          defaultMode: 420
          secretName: dex-grpc-server-cert
