# permissions for end users to view albauths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: albauth-viewer-role
rules:
- apiGroups:
  - dex.betssongroup.com
  resources:
  - albauths
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dex.betssongroup.com
  resources:
  - albauths/status
  verbs:
  - get
