# permissions for end users to edit albauths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: albauth-editor-role
rules:
- apiGroups:
  - dex.betssongroup.com
  resources:
  - albauths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dex.betssongroup.com
  resources:
  - albauths/status
  verbs:
  - get
