{{- if .Values.certs.grpc.create }}
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: dex-grpc-cert-issuer
  labels:
{{ include "dex.labels" . | indent 4 }}
spec:
  ca:
    secretName: {{ .Values.certs.grpc.secret.caName }}
{{- end }}
