{{- if .Values.ldapPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dex.fullname" . }}-ldap
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ldap-bind-password: {{ .Values.ldapPassword | b64enc }}
{{- end }}