name: Build
on:
  push:
    branches:
      - master
      - v*
  pull_request:
    branches: [ master ]

jobs:
  test-build-push:
    name: Test, Build and Push Dex-Operator
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Install kubebuilder
      run: make kubebuilder
    - name: Add kubebuilder path
      run: echo "::add-path::/usr/local/kubebuilder/bin"
    - name: Build
      run: make docker-build
    - name: Log into registry
      run: docker login -u="${{ secrets.QUAY_REGISTRY_USER }}" -p="${{ secrets.QUAY_REGISTRY_TOKEN }}" quay.io
    - name: Push image to registry
      run: make docker-push
    

    
